# Spring properties
spring:
  application:
     name: checkout-service  # Service registers under this name

# HTTP Server
server.port: 3333   # HTTP (Tomcat) port

# Configure this Checkout Order to register with Eureka registration Server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#management.endpoints.web.exposure.include: '*'



